### ISSUE TITLE
Images added via PWA show horizontal in list, but vertical when clicked.

### ISSUE THREAD

**Issue by CorneliousJD** [benjaminjonard/koillection#432] opened 2022-07-15 20:09 UTC
Examples below -- would this be able to get fixed so that it shows in the proper orientation as how the photo was taken when it is uploaded?

![image](https://user-images.githubusercontent.com/724777/179303286-67c745f7-eca8-417e-a009-da911777b42b.png)

![image](https://user-images.githubusercontent.com/724777/179303318-36f0718e-d20f-4eee-82f7-fad82c0451ae.png)

**Comment by benjaminjonard** [comment] 2022-07-16 19:54
I think I have a fix for this issue, but I can't reproduce and test if it works and doesn't break anything else. 
Could you share your image if possible please ?

**Comment by CorneliousJD** [comment] 2022-07-17 02:18
> I think I have a fix for this issue, but I can't reproduce and test if it works and doesn't break anything else. Could you share your image if possible please ?

Sure, here are two examples! I did take these with my phone (Pixel 6 Pro) via the PWA app installed on my phone.

Happy to help with more testing on a :dev branch or something if needed too, or provide more info/examples/etc.

![90iscHH2mIHK305ipTXM_original](https://user-images.githubusercontent.com/724777/179381175-89cad384-3fdc-4ff4-a305-f738dd49b9a0.jpg)

![EKZrCK4F0BptbeSDSsFD_original](https://user-images.githubusercontent.com/724777/179381176-c0667bd8-9953-46b1-9446-3cba16f49c10.jpg)

**Comment by benjaminjonard** [comment] 2022-07-17 14:34
Thanks for your help :+1: , the code generating the thumbnail wasn't taking into account the orientation of the original image.

The problem will be solved in the next release, you'll have to upload your image again though.

**Closed as completed** 2022-07-21 09:35 UTC
Labels: bug
